import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        <StoreProvider>
          <Toaster
            position="top-right"
            gutter={12}
            containerStyle={{ margin: "4px" }}
            toastOptions={{
              success: { duration: 3000 },
              error: { duration: 4000 },
              style: {
                fontSize: "14px",
                fontWeight: "500",
                color: "#202C46",
                textWrap: "nowrap",
                maxWidth: "400px",
                padding: "12px 20px",
              },
            }}
          />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
